### ISSUE TITLE
"Unable to process binding"

### ISSUE THREAD

**Issue by nfriend** [faulknercs/Knockstrap#16]
I'm unable to use any of the custom bindings provided by Knockstrap.  Here's the error message I'm getting (for the `tooltip` binding, in this example):

`Unable to process binding "tooltip: function (){return { title:'Tooltip example'} }"
Message: undefined is not a function`

[Here's a simple jsFiddle that demonstrates the problem](http://jsfiddle.net/NathanFriend/41e5snbg/).

I'm not sure if this is a version-specific issue or if I'm just importing/initializing the libraries incorrectly.  Here's the versions being used in my application (and the jsFiddle example):

- jQuery 1.11.0
- Knockout 3.2.0
- Knockstrap 1.2.0

**Comment by faulknercs** [comment]
Hello,

You missed references for bootstrap files, which are dependencies of knockstrap. If I add them, your code is working: http://jsfiddle.net/faulknercs/0z8ke14k/

**Comment by nfriend** [comment]
Thanks, @faulknercs.  I assumed that the "Bootstrap" requirement listed in the documentation was CSS only.  Most other Bootstrap-wrapping libraries I've worked with (like [UI Bootstrap](http://angular-ui.github.io/bootstrap/)) don't require the Bootstrap JavaScript as a dependency.

It might not hurt to add a note in your documentation that this project depends on Bootstrap's styles *and* scripts.

Thanks again for the help.
