### ISSUE TITLE
Add to cdn

### ISSUE THREAD

**Issue by mika76** [faulknercs/Knockstrap#19]
Could you please add this to a cdn or two?

ie: https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library

**Comment by faulknercs** [comment]
Yes, I can. I will add to cdnjs.
Also, you can use www.rawgit.com as cdn. For example, for version 1.2.0 you can use next url: https://cdn.rawgit.com/faulknercs/Knockstrap/v1.2.0/build/knockstrap.min.js

**Comment by mika76** [comment]
Any idea when?

**Comment by faulknercs** [comment]
When version 1.3.0 will be released. I don't have enough time now, but I hope, it will be soon.

**Comment by faulknercs** [comment]
Actually, cdn could have been used already, I've just forgotten to mention about them in readme.

So for now I would use [jsDelivr (npm)](https://cdn.jsdelivr.net/npm/knockstrap@1.4.1/build/knockstrap.min.js) or [jsDelivr (Github)](https://cdn.jsdelivr.net/gh/faulknercs/Knockstrap@v1.4.1/build/knockstrap.min.js), it can be directly used with with these services ([please see the doc](https://www.jsdelivr.com/?docs=gh)) (though rawgit is still accessible it's deprecated nowadays).

Also added this note to readme.
