### ISSUE TITLE
Use knockstrap with durandal?

### ISSUE THREAD

**Issue by dhanlon** [faulknercs/Knockstrap#22]
I am unable to find any information on using knockstrap with durandal. Seems like it should be possible, as Durandal supports use of custom ko bindings.

Is this supported, or would I need to modify knockstrap to work correctly as a requirejs module?

**Comment by faulknercs** [comment]
Hello,

Knockstrap should work with Durandal without any modifications, it supports requirejs modules.
Just make sure, that Bootstrap 3 is loaded (e.g. via shim config), knockstrap doesn't specify dependency from bootstrap because bootstrap doesn't support requirejs natively.
