### ISSUE TITLE
knockout.js dependency

### ISSUE THREAD

**Issue by gaea44** [faulknercs/Knockstrap#25]
Hi,

I already use knockout on my project ("knockout": "~3.3.0" on my bower.json),
But when i install knockstrap via bower, it add me the dependency "knockout.js": "~3.1.0".

How can i get rid of this dependency and use the "knockout" dependency already defined?

Thanks.

**Comment by faulknercs** [comment]
Hello,

I missed, when knockout has got official bower package, so I'll change dependency to 'knockout' package in next version.

Until this, you could use something like this http://stackoverflow.com/a/23289270

**Comment by spcurry** [comment]
Just curious when the next version is expected? :)

**Comment by faulknercs** [comment]
I hope, it will be available by the end of summer/beginning of autumn :)
I have had a lot of unpredictable issues irl, so I didn't have enough time for my projects.

**Comment by faulknercs** [comment]
New version is released.

**Comment by spcurry** [comment]
Thanks!
