### ISSUE TITLE
[Feature Request] Modal/Popover close event.

### ISSUE THREAD

**Issue by DenEwout** [faulknercs/Knockstrap#30]
Hi,

For popovers @faulknercs suggested to use inject closeFn function in the popover params in order to close a popover on a certain event (see: https://github.com/faulknercs/Knockstrap/issues/8).  I am currently using the closeFn solution in order to react to the closing of a popover (resetting certain stuff/etc...). This allows me to execute some functionalities of the VM linked to the popover when it closes.

I want something similar for modals, the problem here being is, you can also close popovers by clicking anywhere on the modal.  I know this can be disabled by using the static backdrop, but i'd like to keep this behavior and be able to inject some functionality from a VM into the close event (without having to use jQuery inside my VM's if possible). An example of this would be the "action" that can currently be injected in modals when clicking the primary button. Basically I would like to be able to use a "closeAction" that always gets called when the modal closes. (and possibly also for popovers, to get rid of the workaround).

My usecase for this would be the following:
Modals and popovers are often containing forms that have inputs with data-binding. Since the inputs are data-bound they are actually changing certain things. When the modal/popover closes it then becomes possible to implement some sort of cancel on these changes by storing the initial values. 

Sorry for the long read, I hope it's a bit understandable.

Kind regards,

@DenEwout

Edit: updated the bottom part which contained a poor explanation of my usecase.

**Comment by faulknercs** [comment]
If I understand you correctly, for modals you can use event binding and bootstrap events:
`data-bind="modal: {...}, event: { 'hide.bs.modal': hideHandler, 'hidden.bs.modal': hiddenHandler }"`
