### ISSUE TITLE
Progress binding CPU Usage

### ISSUE THREAD

**Issue by pasodoff** [faulknercs/Knockstrap#33]
It appears that in version 1.2.1 that if the `animated` property is set to `true` the browser continuously paints the progress bar.  Turning this option off ensured resulted in the CPU usage returned to normal.

**Comment by faulknercs** [comment]
Animated property simply adds bootstrap's ```active``` css class to progress bar. I checked this at bootsrap's docs page and it also is reproduced. So this issue is related with bootstrap's animation of progress bar.

**Comment by pasodoff** [comment]
You are absolutely correct.  Even if the `.progress-bar-striped` class isn't applied, the active tag causes the constant rendering.

Example:  [JSFiddle](http://jsfiddle.net/9fypstfj/)

My mistake.
