### ISSUE TITLE
String template is not working for popovers

### ISSUE THREAD

**Issue by maz4focus** [faulknercs/Knockstrap#40]
Hi,
in the function "renderPopoverTemplate", the following line didnt work for us:
                    ko.renderTemplate(ko.unwrap(value.template), bindingContext.createChildContext(data), value.templateOptions, document.getElementById(id));

We had to modify it:
                    ko.renderTemplate(ko.unwrap(value.template).name, bindingContext.createChildContext(data), value.template, document.getElementById(id));

We changed the following: 
pass ko.unwrap(value.template).name, not ko.unwrap(value.template),

pass value.template, not value.templateOptions.

Only this way, we were able to have the popover binding work with a registred template.

Kind regards,
Marco

**Comment by faulknercs** [comment]
Hello,

Could you, please, provide code for model, which was passed to popover binding?
I can't reproduce this issue. Please, see this example of usage popover with string template: https://jsfiddle.net/faulknercs/a6r4skp9/ 
It works without any issues.

**Comment by maz4focus** [comment]
Hi Artem, sorry for the late answer. Maybe we used the binding wrong, I think we use the same syntax for the template option, as in the example here: 
https://github.com/faulknercs/Knockstrap/blob/master/examples-src/htmlParts/stringTemplateEngineExamples.html
Passing the template parameter in this manner is how we do it and that way it won't work. See fiddle:
https://jsfiddle.net/xuxac3pf/1/
On the other side, I see on the knockstrap examples that I should pass the template as a string and the templateoptions (such as the engine) separately. So maybe it would be best if we revert our local modification and change our binding...
Kind regards, Marco

**Comment by faulknercs** [comment]
Hello,

Yes, you should pass template options separately from template name in current implementation.
It was done in this way, because I thought, that usage of templates without options is more common than with options, and current syntax is less complex for templates without options.

I think, that I will try to add support of passing single object with name and options for template in next version.

Best regards,
Artem
