### ISSUE TITLE
"if" and "ifnot" template binding not implemented

### ISSUE THREAD

**Issue by maz4focus** [faulknercs/Knockstrap#42]
Compare with knockout default "template" binding. KO has an "if" option that prevents rendering.
This won't work on popover templates. I saw that knockout itself does check that option before calling ko.renderTemplate, so I decided to hack our copy of knockstrap the same way. Here's what's working for us, maybe it could be included in a future knockstrap official release:
In the ko.bindingHandlers.popover object, there's a init and an update function.
In the update, after the call:

// use unwrap to track dependency from template, if it is observable
ko.unwrap(value.template);

I added the following code:
var shouldDisplay = true;
if ('if' in value.template)
    shouldDisplay = ko.utils.unwrapObservable(value.template['if']);
if (shouldDisplay && 'ifnot' in options)
    shouldDisplay = !ko.utils.unwrapObservable(value.template['ifnot']);
if (!shouldDisplay) {
    return;
}

we then simply add the option to our knockstrap html tag:

<p data-bind="text: blabla, popover: { options: { trigger: 'hover' }, data:  blabla, template: { name: 'theTemplate', templateEngine: ko.stringTemplateEngine.instance, if: our_condition } }" ></p>

(I pasted some HTML code here, somehow it's not shown as soon as I post my comment...)
We needed this to prevent knockstrop to show popover's over empty table cells.

**Comment by faulknercs** [comment]
Implemented
