### ISSUE TITLE
Saving Values 

### ISSUE THREAD

**Issue by redowl3** [faulknercs/Knockstrap#43]
Hi, thanks for the library - very helpful, the only issue I'm having is saving information entered into a modal dialog back to the server.  It looks as though it's updating the viewmodel successfully but when I save the original values are being passed back.  I'm using ko.mapping.toJS to send information back.

Any ideas what I'm doing wrong?

**Comment by faulknercs** [comment]
Could you, please, provide example of your code, where this issue occurs?

**Comment by redowl3** [comment]
Hi,

Thanks for the quick response.  I think (?) I've just resolved it - I was
setting the value of the label inside another ko.observable (where self.Comment
is an observable)

 var firstTemplateData = {
                text: 'text',
                label: ko.observable(self.Comment)
            };

instead using of

 var firstTemplateData = {
                text: 'text'
                label: self.Comment
            };

Regards,
Alex

**Comment by faulknercs** [comment]
So, I think, I may close this, if issue has been resolved :)
Feel free to reopen, if you have questions.

**Comment by redowl3** [comment]
Hi, yes it worked fine.

Quick question - is it possible to make the modal dialog box appear on hover?

**Comment by faulknercs** [comment]
I can suggest using of mouseover event, please, see this example: https://jsfiddle.net/faulknercs/y7f2jguu/

**Comment by redowl3** [comment]
Perfect! Thank you.

**Comment by redowl3** [comment]
Hi,

Sorry to bother you again...but is it possible using Knockstrap Modal to fire an
event from the close action? For example fire an ajax request to save the
contents of the modal.

Any help much appreciated,

Thanks

**Comment by faulknercs** [comment]
Hello,

Yes, it is possible via 'hidden.bs.modal' event. Please, look at this example: https://jsfiddle.net/faulknercs/5ofenepa/

**Comment by redowl3** [comment]
Thanks just what I needed!

**Comment by redowl3** [comment]
Hi,

Sorry to bother you, yet again but is it possible to create mulitple events from
within a modal dialog?  I have a modal popup with a 'Save' button as well as the
'x' close button. By hooking up the onclose event my event is fired on both Save
and Close actions, in the background I am saving to a db and looking to avoid
this on just closing if possible.

Thanks again for your help.

**Comment by faulknercs** [comment]
Hello, 

Sorry for not answering so long. Yes, you can use `action` property of footer, if you use default template for modal footer (please, see this: https://jsfiddle.net/faulknercs/zwt96bng/, also see docs for details). Also, you can specify your own template for modal footer and use any buttons with any events with it (please, see this: https://jsfiddle.net/faulknercs/f5at5649/). 
Hope, this will help you.

**Comment by redowl3** [comment]
Hi,

Thank you again for your help, much appreciated.

Thanks,
