### ISSUE TITLE
Constrols not disabled when total items = 0

### ISSUE THREAD

**Issue by dev101** [faulknercs/Knockstrap#46]
When total items is 0, next and last controls are not disabled, and following them causes 0 or **negative** page numbers.
See demo here: https://www.dropbox.com/s/da9o1s3294olm8x/pagingBug.gif?dl=0

**Comment by faulknercs** [comment]
Hello,

Thanks for the report, should be fixed at a9767bd0fe5d06c45bd273e4683537fea4edfedc
Will be included in next release.

Best regards,
Artem

**Comment by faulknercs** [comment]
Released
