### ISSUE TITLE
Is there a way to use foreach in data-binding of modal body object?

### ISSUE THREAD

**Issue by ZackBoyd** [faulknercs/Knockstrap#49]
I would like to pass a ko observable array to my template for the modal body and use foreach to populate the body with a row for each item in the observable array (I'm displaying search results for a location in the modal). I've been able to get the modal to show up and populated data in the header and modal body with a single item example,  but haven't been able to get it to work with foreach and was wondering if it is supported?

**Comment by faulknercs** [comment]
Hello,

Yes, it should be supported. Please, see this examples: 
https://jsfiddle.net/faulknercs/dqqc807f/
https://jsfiddle.net/faulknercs/fpqw4r3d/
Hope, they will help you.

**Comment by ZackBoyd** [comment]
Awesome, those examples were very helpful. I was trying to go off the Knockout template docs and take the approach of the #2 fiddle, but I didn't have it quite right. Thanks again and thanks for putting out these bindings.

**Comment by faulknercs** [comment]
You are welcome!
