### ISSUE TITLE
Tooltip not showing up on disabled button in chrome

### ISSUE THREAD

**Issue by afzal273** [faulknercs/Knockstrap#51]
Is there a way to make tooltip show on a disabled button? I looked up BS documentation and it said to put button inside a div, but even with that the tooltip is showing up only if button is enabled and not if button is disabled.

```
<div style="display: inline-block" data-bind="tooltip: { title: 'Create new Purchase', placement: 'top'}"><button type="button" data-bind="visible: showCreateLinkButton(), enable: $root.isUserAdmin && enableLinkSyncButton, click: $root.createLinkOrder.bind($data, 'create')" class="btn text-center btn-success btn-xs">Create Purchase</button></div>
```

**Comment by afzal273** [comment]
I noticed that tooltips are showing up on disabled buttons in firefox regardless of whether they are wrapped inside divs, but not in chrome either way.

**Comment by faulknercs** [comment]
As far as I can see, issue is not reproducable with the lates Chrome (87.0.4280.88): https://jsfiddle.net/faulknercs/k51dhpym/
![image](https://user-images.githubusercontent.com/1216573/101985319-56917180-3c98-11eb-9d22-fe75f109cd4b.png)

Anyway thanks for the feedback!
