### ISSUE TITLE
Pagination should be accepted url with parameters is better.

### ISSUE THREAD

**Issue by happyendin** [faulknercs/Knockstrap#52]
This is very good plugin with KO and Bootstrap, current I just use the pagination functionality, but it cannot accept the URL with current web page URL you access.

I just want to add a parameter with URL in constructor when init pagination in web page, then for all the pages when click page number or last or first page it can jump to the correct list page.

however i can change the source code by myself in my local, if any helps I would like contribute the code when I finish changes without any issues, can I commit my code in this repo? of course, any review is welcome.

**Comment by faulknercs** [comment]
Hello,

Thanks for feedback!
Not sure, what do you mean about "parameter with URL in constructor". Could you, please, provide more details or example, which covers this use case?

As for code contributing, feel free to make pull requests, I'll review them and then let you know, if everything is okay or not.

Best regards,
Artem

**Comment by faulknercs** [comment]
Since there is no updates, I close this issue. Feel free to reopen
