### ISSUE TITLE
Numeric button values cause f.replace error

### ISSUE THREAD

**Issue by stevekrile** [faulknercs/Knockstrap#53]
When using the button binding, using numeric values causes the code to error:

This WORKS
`                                                <div class="btn-group form-group" data-toggle="buttons" data-bind="radio: Response.Response">
                                                    <label class="btn btn-success">
                                                        <input type="radio" name="options" value="A" />
                                                        A
                                                    </label>
                                                </div>`

And this FAILS

`                                                <div class="btn-group form-group" data-toggle="buttons" data-bind="radio: Response.Response">
                                                    <label class="btn btn-success">
                                                        <input type="radio" name="options" value="1" />
                                                        1
                                                    </label>
                                                </div>`

**Comment by faulknercs** [comment]
Fixed
