### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by matthanson12** [faulknercs/Knockstrap#54]
Forgive me if this is the wrong place (never used github) but the documentation for the pager says "pageSizes" when it should read "pageSize"

https://github.com/faulknercs/Knockstrap/blob/master/examples-src/htmlParts/bindingExamples/pagerExample.html#L74-L78

**Comment by AaronJach** [comment]
Kudos to this discovery - just spent the last hour debugging why I was unable to set page size.
Always the little things....

**Comment by faulknercs** [comment]
Fixed!
