### ISSUE TITLE
How i can work with paging with dynamic data?

### ISSUE THREAD

**Issue by Moggieggwp** [faulknercs/Knockstrap#56]
`<div data-bind="pagination: { currentPage: page, totalCount: total, maxPages: maxPages, directions: directions, boundary: boundary, text: text }"></div>`
Here i see only binding. Where i can change my view by clicking on some number of page? Can I see some examples not only with paging interface, but also with data on view which changed by clicking on paging.
And is it will working with typescript?

**Comment by ambsw-technology** [comment]
I suspect currentPage is bound to an observable.  You would subscribe to that observable and update the view if the value changes.

**Comment by faulknercs** [comment]
Yes, as mentioned above, `page` is observable, so you can subscribe to its changes and use its value as you need: show correct template according to page number, or request required date for that page. You don't have any restrictions how to use it :)

As an example, please see this: https://jsfiddle.net/faulknercs/Lc4mzp5u/
