### ISSUE TITLE
Changing "hidden.bs.modal" event name to "hidden" in Modal.

### ISSUE THREAD

**Issue by Usaga** [faulknercs/Knockstrap#59]
Hi there!

Is it possible to change event name from "hidden.bs.modal" to "hidden" wich Knockstrap (modal) is listening on? I.e. just remove namespace. Or add second event listener "hidden"? I believe it shouldn't break anything.

We are using some plugin (https://github.com/jschr/bootstrap-modal) which patches bootstrap modal and sends "hidden" event instead of original "hidden.bs.modal". I've tried to investigate and change this in used plugin, but no success - I am too lame in JS.

So, what do you think about this? Is it feasible?

**Comment by faulknercs** [comment]
Hello,

Currently event name is hard-coded into modal binding code. So it is not possible to change event name now without modifying knockstrap code. I didn't know, that some plugins change event name.
But I think, I can add setting for event name to modal binding, so you would have possibility to change it. 

I see the next option how it can be implemented: it would be possible to change event name globally via ```ko.bindingHandlers.modal.defaults.events.hidden``` or via passing setting directly to particular binding (like ```data-bind="modal: { events: { hidden: 'hidden'} ... }"```).

**Comment by Usaga** [comment]
The options for event name would be great to!

**Comment by faulknercs** [comment]
Implemented
