### ISSUE TITLE
How to use afterRender in templateOptions in Popover?

### ISSUE THREAD

**Issue by Le-Sy-Hoang** [faulknercs/Knockstrap#70]
I'm struggling to make use of templateOptions, particularly afterRender callback. Can you update your examples to include a demo for templateOptions?

**Comment by faulknercs** [comment]
Hello!

You can pass `templateOptions` alongside the `template` property to the popover binding.
Please, see this example: https://jsfiddle.net/faulknercs/7Le6noj8/

Also please note that `templateOptions` is used only if you're using some template for popover.

**Comment by Le-Sy-Hoang** [comment]
Thank you, @faulknercs
